import { useEffect, useState } from 'react';
import { BookOpen, LayoutDashboard, ShoppingBag, Settings, LogOut, Plus, ExternalLink, Search } from 'lucide-react';
import { api, money, categories } from '../../frontend/src/api.js';
import { Brand, Modal, Field, ErrorMessage, Empty, Toast } from '../../frontend/src/components.jsx';
import UploadNotes from './UploadNotes.jsx';

const blankNote = () => ({ title: '', category: 'PET', description: '', topics: '', badge: 'Exam essentials', language: 'Hindi + English', price: 149, originalPrice: 299, pages: 180, chapters: 12, published: true });
const sections = [['Overview', LayoutDashboard], ['Catalogue', BookOpen], ['Orders', ShoppingBag], ['Offers', Settings]];

export default function App() {
  const [uploading, setUploading] = useState(null);
  const [user, setUser] = useState(null), [checking, setChecking] = useState(true);
  const [password, setPassword] = useState(''), [section, setSection] = useState('Overview');
  const [notes, setNotes] = useState([]), [orders, setOrders] = useState([]), [settings, setSettings] = useState(null);
  const [loading, setLoading] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [toast, setToast] = useState('');
  const [query, setQuery] = useState(''), [editor, setEditor] = useState(null), [deleting, setDeleting] = useState(null), [formError, setFormError] = useState('');
  useEffect(() => { api('/admin/session').then(setUser).catch(e => { if (e.status !== 401) setError(e.message); }).finally(() => setChecking(false)); }, []);
  useEffect(() => { if (user) refresh(); }, [user]);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 4500); return () => clearTimeout(timer); } }, [toast]);
  async function refresh() {
    setLoading(true); setError('');
    try { const [n, o, s] = await Promise.all([api('/admin/notes'), api('/admin/orders'), api('/settings')]); setNotes(n); setOrders(o); setSettings(s); }
    catch (e) { setError(e.message); if (e.status === 401) setUser(null); }
    finally { setLoading(false); }
  }
  async function login(event) {
    event.preventDefault(); setBusy(true); setError('');
    try { setUser(await api('/admin/login', { method: 'POST', body: { password } })); setPassword(''); } catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  async function mutate(action, message, close) {
    setBusy(true); setError(''); setFormError('');
    try { await action(); close?.(); setToast(message); }
    catch (e) { if (editor || deleting) setFormError(e.message); else setError(e.message); if (e.status === 401) { setUser(null); setEditor(null); setDeleting(null); setError(e.message); } }
    finally { setBusy(false); }
  }
  const needle = query.trim().toLowerCase();
  const filteredNotes = notes.filter(n => `${n.title} ${n.category}`.toLowerCase().includes(needle));
  const filteredOrders = orders.filter(o => `${o.id} ${o.name} ${o.email} ${o.title} ${o.status}`.toLowerCase().includes(needle));
  const change = (key, value) => setEditor(current => ({ ...current, [key]: value }));
  if (checking) return <main className="admin-loading" role="status">Loading admin session…</main>;
  if (!user) return <main className="admin-login"><div className="admin-login-card"><Brand/><span className="admin-eyebrow">BRIGHT FUTURE • ADMINISTRATION</span><h1>Welcome back.</h1><p>Manage your notes, orders, and offers.</p><form onSubmit={login}><Field label="Password"><input type="password" autoComplete="current-password" required maxLength={256} value={password} onChange={e => setPassword(e.target.value)}/></Field><ErrorMessage message={error}/><button className="admin-primary" disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</button></form><p className="admin-muted">Local demo credentials are documented in the project README.</p><a href="/frontend/">← Back to storefront</a></div><div className="admin-login-art"><BookOpen size={64}/><h2>A brighter future,<br/>behind every page.</h2><p>Your workspace for better learning.</p></div></main>;
  return <div className="admin-shell"><aside className="admin-sidebar"><Brand/><span className="admin-eyebrow">WORKSPACE</span><nav aria-label="Admin navigation">{sections.map(([name, Icon]) => <button key={name} className={section === name ? 'active' : ''} aria-current={section === name ? 'page' : undefined} onClick={() => { setSection(name); setQuery(''); setError(''); }}><Icon size={20}/>{name}</button>)}</nav><div className="admin-sidebar-bottom"><a href="/frontend/"><ExternalLink size={18}/>View storefront</a><button disabled={busy} onClick={() => mutate(async () => { await api('/admin/logout', { method: 'POST' }); setUser(null); setNotes([]); setOrders([]); }, 'Signed out.')}><LogOut size={18}/>Sign out</button><small>Demo workspace · 9161868600</small></div></aside>
    <main className="admin-main"><header className="admin-header"><div><span className="admin-eyebrow">BRIGHT FUTURE NOTES</span><h1>{section}</h1><p>{section === 'Overview' ? 'A clear view of your learning community.' : section === 'Catalogue' ? 'Create and manage your exam preparation notes.' : section === 'Orders' ? 'Review orders and manage access.' : 'Keep your storefront offer up to date.'}</p></div><span className="admin-demo">Administration</span></header>
    <ErrorMessage message={error}/>{error && <button className="admin-secondary" onClick={refresh} disabled={loading}>Retry loading</button>}
    {loading ? <p role="status">Loading workspace…</p> : <>
    {section === 'Overview' && <><div className="admin-metrics">{[['Published notes', notes.filter(n => n.published).length], ['Orders', orders.length], ['Pending orders', orders.filter(o => o.status === 'Pending').length], ['Order value', money(orders.filter(o => o.status !== 'Cancelled').reduce((sum, o) => sum + o.amount, 0))]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><section className="admin-panel"><div className="admin-panel-title"><h2>Recent orders</h2><button className="admin-secondary" onClick={() => setSection('Orders')}>View all orders</button></div><OrderTable orders={orders.slice(0, 5)}/></section><div className="admin-info"><strong>A workspace for demonstration.</strong><p>Only verified Razorpay payments unlock downloads. Changing an order status here cannot grant paid access.</p></div></>}
    {section === 'Catalogue' && <section className="admin-panel"><div className="admin-panel-title"><SearchField value={query} onChange={setQuery} label="Search catalogue"/><button className="admin-primary" onClick={() => { setEditor(blankNote()); setFormError(''); }}><Plus size={18}/>Add notes</button></div>{filteredNotes.length ? <div className="admin-table-wrap"><table><thead><tr><th>Notes</th><th>Price</th><th>Visibility</th><th>Actions</th></tr></thead><tbody>{filteredNotes.map(n => <tr key={n.id}><td><strong>{n.title}</strong><small>{n.category} · {n.pages} pages</small><small>{n.file ? n.file.name : 'No PDF uploaded'}</small></td><td>{money(n.price)}<small>Original {money(n.originalPrice)}</small></td><td><span className={`admin-status ${n.published ? 'good' : ''}`}>{n.published ? 'Published' : 'Draft'}</span></td><td><div className="admin-actions"><button className="admin-secondary" aria-label={`Upload PDF for ${n.title}`} onClick={() => setUploading(n)}>{n.file ? 'Replace PDF' : 'Upload PDF'}</button><button className="admin-secondary" aria-label={`Edit ${n.title}`} onClick={() => { setEditor({ ...n }); setFormError(''); }}>Edit</button><button className="admin-danger" aria-label={`Delete ${n.title}`} onClick={() => { setDeleting(n); setFormError(''); }}>Delete</button></div></td></tr>)}</tbody></table></div> : <Empty title="No notes found">Add notes or try another search.</Empty>}</section>}
    {section === 'Orders' && <section className="admin-panel"><div className="admin-panel-title"><SearchField value={query} onChange={setQuery} label="Search orders"/><button className="admin-secondary" onClick={refresh}>Refresh</button></div><OrderTable orders={filteredOrders} busy={busy} onStatus={(order, status) => mutate(async () => { const updated = await api(`/admin/orders/${order.id}`, { method: 'PUT', body: { status } }); setOrders(items => items.map(o => o.id === updated.id ? updated : o)); }, 'Order status updated.')}/></section>}
    {section === 'Offers' && settings && <section className="admin-panel admin-offers"><h2>Storefront offer</h2><p className="admin-muted">Update the offer banner. Catalogue prices are managed separately.</p><form onSubmit={e => { e.preventDefault(); mutate(async () => setSettings(await api('/admin/settings', { method: 'PUT', body: { ...settings, discount: Number(settings.discount) } })), 'Offer saved.'); }}><Field label="Offer title"><input required minLength={3} maxLength={100} value={settings.offerTitle} onChange={e => setSettings({ ...settings, offerTitle: e.target.value })}/></Field><Field label="Offer description"><textarea required minLength={3} maxLength={250} value={settings.offerSubtitle} onChange={e => setSettings({ ...settings, offerSubtitle: e.target.value })}/></Field><Field label="Advertised discount (%)"><input type="number" required min={0} max={90} step={1} value={settings.discount} onChange={e => setSettings({ ...settings, discount: e.target.value })}/></Field><p className="admin-muted">Contact number: 9161868600</p><button className="admin-primary" disabled={busy}>{busy ? 'Saving…' : 'Save offer'}</button></form></section>}
    </>}</main><Toast message={toast}/>
    {uploading && <UploadNotes note={uploading} onClose={() => setUploading(null)} onSaved={updated => { setNotes(items => items.map(note => note.id === updated.id ? updated : note)); setUploading(null); setToast('Notes PDF uploaded.'); }}/>} 
    {editor && <Modal title={editor.id ? 'Edit notes' : 'Add notes'} wide onClose={() => { if (!busy) setEditor(null); }}><form className="admin-note-form" onSubmit={e => { e.preventDefault(); mutate(async () => { const body = { ...editor }; for (const key of ['price', 'originalPrice', 'pages', 'chapters']) body[key] = Number(body[key]); const saved = await api('/admin/notes' + (editor.id ? '/' + editor.id : ''), { method: editor.id ? 'PUT' : 'POST', body }); setNotes(items => editor.id ? items.map(n => n.id === saved.id ? saved : n) : [...items, saved]); }, 'Notes saved.', () => setEditor(null)); }}><Field label="Title"><input required minLength={3} maxLength={100} value={editor.title} onChange={e => change('title', e.target.value)}/></Field><Field label="Category"><select value={editor.category} onChange={e => change('category', e.target.value)}>{categories.map(c => <option key={c}>{c}</option>)}</select></Field><Field label="Description"><textarea required minLength={5} maxLength={300} value={editor.description} onChange={e => change('description', e.target.value)}/></Field><Field label="Topics"><input required minLength={3} maxLength={250} value={editor.topics} onChange={e => change('topics', e.target.value)}/></Field><div className="admin-form-grid">{[['price', 'Sale price (₹)'], ['originalPrice', 'Original price (₹)'], ['pages', 'Pages'], ['chapters', 'Chapters']].map(([key, label]) => <Field key={key} label={label}><input type="number" required min={1} max={100000} step={1} value={editor[key]} onChange={e => change(key, e.target.value)}/></Field>)}<Field label="Badge"><input required maxLength={40} value={editor.badge} onChange={e => change('badge', e.target.value)}/></Field><Field label="Language"><input required minLength={2} maxLength={50} value={editor.language} onChange={e => change('language', e.target.value)}/></Field></div><label className="admin-check"><input type="checkbox" checked={editor.published} onChange={e => change('published', e.target.checked)}/>Published on storefront</label><ErrorMessage message={formError}/><div className="admin-actions"><button type="submit" className="admin-primary" disabled={busy}>{busy ? 'Saving…' : 'Save notes'}</button><button type="button" className="admin-secondary" disabled={busy} onClick={() => setEditor(null)}>Cancel</button></div></form></Modal>}
    {deleting && <Modal title="Delete notes" onClose={() => { if (!busy) setDeleting(null); }}><p>Delete “{deleting.title}” from the catalogue? Existing order records will be retained.</p><ErrorMessage message={formError}/><div className="admin-actions"><button className="admin-danger" disabled={busy} onClick={() => mutate(async () => { await api('/admin/notes/' + deleting.id, { method: 'DELETE' }); setNotes(items => items.filter(n => n.id !== deleting.id)); }, 'Notes deleted.', () => setDeleting(null))}>{busy ? 'Deleting…' : 'Confirm delete'}</button><button className="admin-secondary" disabled={busy} onClick={() => setDeleting(null)}>Cancel</button></div></Modal>}
  </div>;
}

function SearchField({ value, onChange, label }) { return <label className="admin-search"><Search size={19}/><input type="search" aria-label={label} placeholder={label} value={value} onChange={e => onChange(e.target.value)}/></label>; }
function OrderTable({ orders, onStatus, busy }) {
  return orders.length ? <div className="admin-table-wrap"><table><thead><tr><th>Order / student</th><th>Notes</th><th>Amount</th><th>Status</th></tr></thead><tbody>{orders.map(o => <tr key={o.id}><td><strong>{o.name}</strong><small>{o.email}</small><small>{o.id} · {new Date(o.createdAt).toLocaleDateString('en-IN')}</small></td><td>{o.title}</td><td>{money(o.amount)}</td><td>{onStatus ? <select aria-label={`Status for ${o.id}`} value={o.status} disabled={busy} onChange={e => onStatus(o, e.target.value)}>{[...new Set([o.status, 'Pending', 'Cancelled'])].map(s => <option key={s}>{s}</option>)}</select> : <span className={`admin-status ${o.status === 'Paid' ? 'good' : ''}`}>{o.status}</span>}</td></tr>)}</tbody></table></div> : <Empty title="No orders found">Orders will appear here when students try checkout.</Empty>;
}
