import PreviewModal from './PreviewModal.jsx';
import CheckoutModal from './CheckoutModal.jsx';
import { useEffect, useState } from 'react';
import { ArrowRight, ArrowUpRight, BookOpen, Check, CheckCircle2, ChevronDown, Download, FileText, Gift, GraduationCap, Headphones, Layers, Menu, MessageCircle, Search, ShieldCheck, Smartphone, Sparkles, Target, UserRound, Wallet, X, Zap, ClipboardCheck, Languages, LogOut } from 'lucide-react';
import { api, categories, money, whatsapp } from './api.js';
import { Brand, Modal, BookCover, Field, ErrorMessage, Empty, Toast } from './components.jsx';

const benefits = [ [Target, 'Made for your exam', 'Focused content that keeps your preparation on track.'], [ClipboardCheck, 'Syllabus-aligned', 'Organised topics, so you know exactly what to study.'], [Languages, 'Easy to understand', 'Clear explanations in Hindi and English.'], [Smartphone, 'Study anywhere', 'Mobile-friendly PDFs for learning on the go.'], [Wallet, 'Big value. Small price.', 'Quality study material that fits your budget.'], [Zap, 'Ready when you are', 'Preview the material and start your next chapter.'] ];

export default function App() {
  const [notes, setNotes] = useState([]), [settings, setSettings] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const [category, setCategory] = useState('All Notes'), [search, setSearch] = useState(''), [sort, setSort] = useState('popular'), [menu, setMenu] = useState(false);
  const [modal, setModal] = useState(null), [user, setUser] = useState(null), [orders, setOrders] = useState([]), [toast, setToast] = useState(''), [openFaq, setOpenFaq] = useState(0);
  async function load() { setLoading(true); setError(''); try { const [items, config, student] = await Promise.all([api('/notes'), api('/settings'), api('/session')]); setNotes(items); setSettings(config); setUser(student); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 4500); return () => clearTimeout(timer); } }, [toast]);
  function chooseCategory(value) { setCategory(value); setSearch(''); setMenu(false); document.getElementById('notes')?.scrollIntoView({ behavior: 'smooth' }); }
  async function library() { setModal({ type: 'library', loading: true }); try { setOrders(await api('/orders')); setModal({ type: 'library' }); } catch (e) { setModal({ type: 'library', error: e.message }); } }
  async function logout() { try { await api('/session', { method: 'DELETE' }); setUser(null); setOrders([]); setModal(null); setToast('Session ended.'); } catch (e) { setToast(e.message); } }
  const filtered = notes.filter(note => (category === 'All Notes' || note.category === category) && (note.title + note.topics).toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === 'low' ? a.price - b.price : sort === 'high' ? b.price - a.price : 0);
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <div className="announcement"><div className="container announcement-inner"><span><Sparkles size={14}/> Your next chapter starts here. <b>Premium notes. Special prices.</b></span><a href={whatsapp()} target="_blank" rel="noreferrer"><MessageCircle size={14}/> 9161868600 <ArrowUpRight size={13}/></a></div></div>
    <header className="site-header"><div className="container nav-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation"><a className="active" href="#main">Home</a><a href="#notes" onClick={() => chooseCategory('All Notes')}>All Notes</a><a href="#why-us">Why Bright Future?</a><a href="#help">Contact Us</a></nav><button className="button button-blue login-button" onClick={() => user ? library() : setModal({ type: 'login' })}><UserRound size={17}/>{user ? 'My Library' : 'Login / Register'}</button><button className="icon-button mobile-toggle" onClick={() => setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu ? <X/> : <Menu/>}</button></div>{menu && <nav className="mobile-nav" aria-label="Mobile navigation"><a href="#main" onClick={() => setMenu(false)}>Home</a><button onClick={() => chooseCategory('All Notes')}>All Notes</button>{categories.map(item => <button key={item} onClick={() => chooseCategory(item)}>{item}</button>)}<a href="#why-us" onClick={() => setMenu(false)}>Why Bright Future?</a></nav>}</header>
    <main id="main">
      <section className="hero"><div className="container hero-inner"><div className="hero-copy"><span className="eyebrow"><span className="tiny-line"/> YOUR AMBITION. OUR COMMITMENT.</span><h1>Prepare better.<br/>Dream bigger.<br/><span>Achieve more.</span><svg className="headline-swoosh" viewBox="0 0 310 15" aria-hidden="true"><path d="M3 12Q155 -5 307 8" fill="none" stroke="currentColor" strokeWidth="4" strokeLinecap="round"/></svg></h1><p className="hero-description">Your brighter future starts with the right notes.<br className="desktop-break"/> Exam-focused study material, made simple.</p><p className="hindi-copy" lang="hi">आपकी मेहनत, सही दिशा में। सफलता की तैयारी, हमारे साथ।</p><div className="hero-actions"><a className="button button-orange" href="#notes">Explore Notes <ArrowRight size={18}/></a><a className="button button-whatsapp" href={whatsapp('Hello! I would like to know more about Bright Future Notes.')} target="_blank" rel="noreferrer"><MessageCircle size={18}/> Chat on WhatsApp</a></div><div className="hero-reassurance"><span><CheckCircle2/> Exam-oriented</span><span><CheckCircle2/> Hindi + English</span><span><CheckCircle2/> Budget-friendly</span></div></div><div className="hero-visual"><div className="hero-visual-grid"/><span className="visual-kicker">SMALL STEPS. BIG POSSIBILITIES.</span><div className="floating-label"><span><GraduationCap size={22}/></span><div>Built for your success<small>Learn today. Lead tomorrow.</small></div></div><div className="book-stack"><div className="back-book"><BookCover category="PET" variant={1} hero/></div><div className="front-book"><BookCover category="CTET" hero/></div></div><div className="offer-sticker"><span>UP TO</span><strong>{settings?.discount ?? 50}%</strong><b>OFF</b><small>SPECIAL OFFER</small></div><div className="floating-pdf"><FileText size={22}/><span>Read. Revise. Repeat.<small>Your preparation, in your pocket.</small></span><CheckCircle2 size={18}/></div><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="visual-star">✦</span></div></div></section>
      <section className="container stats-bar" aria-label="Our study material"><Stat icon={Layers} value="5" label="Exam categories"/><Stat icon={FileText} value="PDF notes" label="Study on any device"/><Stat icon={Wallet} value="₹149 onwards" label="Quality within reach"/><Stat icon={Headphones} value="WhatsApp support" label="A little help along the way"/></section>
      <section className="container notes-section" id="notes"><div className="section-heading"><div><span className="eyebrow">THE RIGHT NOTES. THE RIGHT START.</span><h2>One step closer to <span>your goal.</span></h2><p>Find your exam. Pick your notes. Make every study session count.</p></div><span className="soft-badge"><ShieldCheck size={15}/> Carefully curated material</span></div><div className="catalog-toolbar"><div className="category-tabs" aria-label="Exam categories">{['All Notes', ...categories].map(item => <button key={item} className={category === item ? 'selected' : ''} onClick={() => setCategory(item)} aria-pressed={category === item}>{item === 'All Notes' && <Layers size={15}/>} {item}</button>)}</div><div className="catalog-search"><Search size={17}/><input aria-label="Search notes" placeholder="Search your notes..." value={search} onChange={e => setSearch(e.target.value)}/></div></div><div className="results-row"><span>{loading ? 'Loading your next chapter…' : `${filtered.length} study packs to get you started`}</span><label>Sort by: <select aria-label="Sort notes" value={sort} onChange={e => setSort(e.target.value)}><option value="popular">Featured</option><option value="low">Price: Low to high</option><option value="high">Price: High to low</option></select></label></div>
      <ErrorMessage message={error}/>{error && <button className="button button-outline" onClick={load}>Try again</button>}{loading ? <div className="notes-grid">{[0,1,2,3,4].map(i => <div key={i} className="skeleton"/>)}</div> : !error && (filtered.length ? <div className="notes-grid">{filtered.map(note => <NoteCard key={note.id} note={note} onPreview={() => setModal({ type: 'preview', note })} onBuy={() => setModal({ type: 'checkout', note })}/>)}</div> : <Empty title="No notes found">Try a different search or select another exam category. <button className="text-button" onClick={() => { setSearch(''); setCategory('All Notes'); }}>Clear filters</button></Empty>)}<div className="catalog-footnote"><FileText size={15}/> Not sure where to start? Preview a free sample before you choose.</div></section>
      <section className="why-section" id="why-us"><div className="container"><div className="section-heading centered"><span className="eyebrow">A BETTER WAY TO PREPARE</span><h2>Your hard work deserves<br/><span>the right study partner.</span></h2><p>Thoughtfully put together. Easy to follow. Made for your journey.</p></div><div className="benefits-grid">{benefits.map(([Icon, title, copy]) => <article className="benefit" key={title}><div className="benefit-icon"><Icon size={24}/></div><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
      <section className="container offer-section"><div className="offer-banner"><div className="offer-gift"><Gift size={44}/></div><div className="offer-copy"><span className="eyebrow">SPECIAL PRICES. EXTRA MOTIVATION.</span><h2>{settings?.offerTitle || 'A little investment. A brighter future.'}</h2><p>{settings?.offerSubtitle || 'Give your preparation the right direction with exam-focused notes at special prices.'}</p></div><a className="button button-orange" href="#notes">Find My Notes <ArrowRight size={18}/></a></div></section>
      <section className="container help-section" id="help"><div className="help-copy"><span className="eyebrow">WE’RE HERE TO HELP</span><h2>A question today.<br/><span>More clarity tomorrow.</span></h2><p>Need help choosing the right notes? Let’s talk about your preparation.</p><a className="contact-link" href={whatsapp()} target="_blank" rel="noreferrer"><span><MessageCircle size={24}/></span><div><small>MESSAGE US ON WHATSAPP</small><strong>+91 9161868600 <ArrowUpRight size={18}/></strong></div></a></div><div className="faq-list">{[['Which exams do these notes cover?', 'Explore study packs for PET, CTET, Bihar STET, BPSC TRE 4.0, and Bihar Police SI. Each pack focuses on the topics relevant to that exam.'], ['Can I see a sample before buying?', 'Yes. Select Preview on a notes card to read the first two pages of its uploaded PDF. The remaining pages stay locked until payment.'], ['How do I access my notes?', 'Start a student session and complete Razorpay checkout. After payment is verified, download the same uploaded PDF from My Library.'], ['Are the notes available in Hindi?', 'The planned study packs include Hindi and English explanations. Current previews demonstrate the layout using sample content.']].map(([q, a], i) => <div className={`faq-item ${openFaq === i ? 'open' : ''}`} key={q}><button aria-expanded={openFaq === i} aria-controls={`faq-${i}`} onClick={() => setOpenFaq(openFaq === i ? -1 : i)}>{q}<ChevronDown size={18}/></button>{openFaq === i && <p id={`faq-${i}`}>{a}</p>}</div>)}</div></section>
      <div className="closing-ribbon"><GraduationCap size={22}/><span>Learn today. <b>Lead tomorrow.</b></span><span className="ribbon-divider"/><span lang="hi">आपके उज्ज्वल भविष्य की शुरुआत यहाँ से।</span></div>
    </main>
    <footer className="site-footer"><div className="container footer-top"><div><Brand/><p>Making exam preparation simpler,<br/>one chapter at a time.</p></div><div><h3>Explore notes</h3><div className="footer-categories">{categories.map(item => <button key={item} onClick={() => chooseCategory(item)}>{item}</button>)}</div></div><div><h3>Let’s stay connected</h3><a href={whatsapp()} target="_blank" rel="noreferrer"><MessageCircle size={17}/> WhatsApp: 9161868600</a><a href="tel:+919161868600"><Headphones size={17}/> Talk to our team</a><a href="/admin/"><ShieldCheck size={17}/> Admin panel</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Bright Future Institute & Media Solution.</span><span>PDF study material · Secure Razorpay checkout</span></div></footer>
    {modal?.type === 'preview' && <PreviewModal note={modal.note} onClose={() => setModal(null)} onBuy={() => setModal({ type: 'checkout', note: modal.note })}/>}
    {(modal?.type === 'login' || modal?.type === 'checkout') && <CheckoutModal modal={modal} user={user} setUser={setUser} onClose={() => setModal(null)} onSuccess={order => { setModal({ type: 'success', order }); setToast('Payment verified. Your PDF is ready.'); }} onLogin={() => { setModal(null); setToast('Your student session is ready.'); }}/ >}
    {modal?.type === 'success' && <Modal title="Your next chapter is ready" onClose={() => setModal(null)}><div className="success-panel"><div className="success-icon"><CheckCircle2 size={38}/></div><h3>You’re all set!</h3><p>{modal.order.title}</p><span className="soft-badge">{modal.order.id}</span><p className="muted">Payment confirmed. Download the full PDF uploaded for these notes.</p><a className="button button-blue" href={`/api/orders/${modal.order.id}/download`} download><Download size={17}/> Download notes</a><button className="text-button" onClick={library}>Go to My Library <ArrowRight size={16}/></button></div></Modal>}
    {modal?.type === 'library' && <Modal title="My Library" onClose={() => setModal(null)} wide><div className="library-heading"><p>Welcome, <b>{user?.name}</b>. Keep your next chapter close.</p><button className="text-button" onClick={logout}><LogOut size={16}/> End session</button></div><p className="notice">Your purchases are linked to this browser for 30 days. Keep your order ID for support. Full PDFs are available only for verified payments.</p><ErrorMessage message={modal.error}/>{modal.loading ? <p>Loading your library…</p> : orders.length ? orders.map(order => <div className="library-item" key={order.id}><span className="benefit-icon"><BookOpen size={22}/></span><div><h3>{order.title}</h3><small>{order.id} · {order.status}</small></div>{order.canDownload && order.hasFile && <a className="button button-outline" href={`/api/orders/${order.id}/download`} download><Download size={16}/>Download notes</a>}{!order.canDownload && order.status !== 'Cancelled' && notes.some(note => note.id === order.noteId) && <button className="button button-blue" onClick={() => setModal({ type: 'checkout', note: notes.find(note => note.id === order.noteId) })}>Pay now</button>}</div>) : !modal.error && <Empty title="Your next chapter is waiting">Preview a study pack and complete payment to unlock its full PDF.</Empty>}</Modal>}
    <Toast message={toast}/>
  </>;
}
function Stat({ icon: Icon, value, label }) { return <div className="stat"><span><Icon size={23}/></span><div><strong>{value}</strong><small>{label}</small></div></div>; }
function NoteCard({ note, onPreview, onBuy }) {
  return <article className="note-card"><div className="card-art"><BookCover category={note.category} variant={categories.indexOf(note.category)}/><span className="card-badge">{note.badge}</span><span className="pdf-badge"><FileText size={12}/> PDF</span></div><div className="card-content"><span className="card-category">{note.category === 'PET' ? 'PET 2026' : note.category}</span><h3>{note.title}</h3><p>{note.description}</p><div className="card-meta"><span><FileText size={13}/>{note.pages} pages</span><span><Languages size={13}/>{note.language}</span></div><div className="price-row"><strong>{money(note.price)}</strong><del>{money(note.originalPrice)}</del><span>{Math.round((1 - note.price / note.originalPrice) * 100)}% off</span></div><div className="card-actions"><button className="button button-outline" onClick={onPreview}><BookOpen size={14}/> Preview</button><button className="button button-blue" onClick={onBuy}>Buy now <ArrowUpRight size={15}/></button></div></div></article>;
}